import math

print('Enter a')
a = int(input())
print('Enter x')
x = int(input())
G = 4*(-4*pow(x,2)+a*x+5*pow(x,2))/-20*pow(a,2)+28*a*x+3*pow(x,2)
print('Result')
print(G)

print('Enter a')
a = int(input())
print('Enter x')
x = int(input())
F = math.atan(24*pow(a,2)-25*a*x+6*pow(x,2))
print('Result')
print(F)

print('Enter a')
a = int(input())
print('Enter x')
x = int(input())
Y = math.log(2*pow(a,2)-7*a*x+6*pow(x,2)+1)
print('Result')
print(Y)
